### ISSUE TITLE
So many thanks

### ISSUE THREAD

**Issue by stuscs9826** [ahfuzhang/victoria-metrics-1.72.0#1]
最近看vm，发现了作者的宝藏仓库，非常感谢，让我献出我的膜拜。
但是发现作者有些注释可能是写的不太对。

**Comment by mzk1234567-mzk** [comment]
怎么样才能加到作者的微信，联系到您，有很多问题想请教作者

**Comment by ahfuzhang** [comment]
> 最近看vm，发现了作者的宝藏仓库，非常感谢，让我献出我的膜拜。 但是发现作者有些注释可能是写的不太对。

欢迎多提意见。或者把你认为正确的部分 merge 进来。谢谢。

**Comment by ahfuzhang** [comment]
> 怎么样才能加到作者的微信，联系到您，有很多问题想请教作者

邮箱：ahfu@qq.com
